version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /home/php7encode/projects/devops
hooks:
  ApplicationStart:
    - location: gitStatus.sh
      timeout: 300
      runas: php7encode

  ValidateService:
    - location: encrypt.sh
      timeout: 300
      runas: php7encode

  # ValidateServices:
  #   - location: scripts/validateservice.sh
  #     timeout: 300