version: 0.0
os: linux
files:
  - source: /
    destination: /home/php7encode/files
hooks:
  BeforeInstall:
      - location: gitStatus.sh
        timeout: 300
        runas: root 

  AfterInstall:
      - location: encrypt.sh
        timeout: 300
        runas: root 
        
  ApplicationStart:
    - location: gulp.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: artifact.sh
      timeout: 300
      runas: php7encode
