version: 0.0
os: linux
files:
  - source: /appspec.yml
    destination: /home/php7encode/projects/devops
hooks:
  AfterInstall:
      - location: backup.sh
        timeout: 300
        runas: root 

  BeforeInstall:
      - location: gitStatus.sh
        timeout: 300
        runas: root 
        
  ApplicationStart:
    - location: encrypt.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: gulp.sh
      timeout: 300
      runas: root
